In [16]:
import pandas as pd

In [ ]:
df = pd.read_csv("all_g.csv").fillna("None").astype('str')

exemple = {'Pokemon': 'kadabra', 'Type 1': {'Psy': 'correct'}, 'Type 2': {'None': 'wrong'}, "Stade d'évolution": {'2': 'wrong'}, 'Entièrement évolué': {'Non': 'wrong'}, 'Couleur': {'Jaune;Marron': 'wrong'}, 'Habitat': {'city': 'wrong', 'ruin': 'wrong'}, 'Gen': {2: 'more'}}
wanted_pokemon = {}
df

,Pokemon,Type 1,Type 2,Stade d'évolution,Entièrement évolué,Couleur,Habitat,Gen
0,Bulbizarre,Plante,Poison,2,Non,[Vert],"[forest, jungle]",1
1,Herbizarre,Plante,Poison,2,Non,"[Vert, Rose]","[forest, jungle]",1
2,Florizarre,Plante,Poison,3,Oui,"[Vert, Rose]","[forest, jungle]",1
3,Salamèche,Feu,None,1,Non,[Orange],"[mountain, volcano]",1
4,Reptincel,Feu,None,2,Non,[Rouge],"[mountain, volcano]",1
...,...,...,...,...,...,...,...,...
488,Phione,Eau,None,1,Oui,[Bleu],"[ocean, tropicalSea]",4
489,Manaphy,Eau,None,1,Oui,[Bleu],[ocean],4
490,Darkrai,Ténèbres,None,1,Oui,[Noir],"[city, forest]",4
491,Shaymin,Plante,None,1,Oui,[Vert],"[city, forest]",4
492,Arceus,Normal,None,1,Oui,"[Blanc, Jaune]",[unknown],4

In [ ]:
def process_guess(df : pd.DataFrame, guess : dict):
    df_copy = df.copy(deep=True)
    bool_keys = ['Type 1', 'Type 2', "Stade d'évolution",'Entièrement évolué']
    for column in bool_keys:
       df_copy = filter_bool_key(df_copy,column,guess)
    df_copy = filter_gen(df_copy,guess)
    return df_copy


def filter_bool_key(df : pd.DataFrame, key : str, guess : dict):
    guess_key : dict = guess.get(key)
    for value,bool in guess_key.items():
        if bool=='correct':
            # self.wanted_pokemon = ...
            df = df[df[key]==value]
        elif bool=='wrong':
            df = df[df[key]!=value]
        elif bool=='partial':
            df = df[df["Type 1"]==value] if key=="Type 2" else df[df["Type 2"]==value]
    
    return df

def filter_gen(df,guess):

    gen_guessed = list(guess.get('Gen', {}).keys())[0]
    value = guess.get('Gen',{}).get(gen_guessed)
    if value=='equal':
        return df[df['Gen']==gen_guessed]
    
    return df[df['Gen']>gen_guessed] if value=='more' else df[df['Gen']<gen_guessed]


def filter_color(df,guess):

In [63]:
process_guess(df,exemple)

,Pokemon,Type 1,Type 2,Stade d'évolution,Entièrement évolué,Couleur,Habitat,Gen
474,Gallame,Psy,Combat,3,Oui,"[Blanc, Vert]",[city],4